---
title: "Duração de mandato nas Secretarias Estaduais de Saúde"
author: "Alexandra Emanuela Novais Silva"
date: "2024-09-04"
output: html_document
subtitle: "uma análise de como o gênero afeta o tempo dos mandatos nas regiões brasileiras"
---


```{r include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
options(repos = c(CRAN = "https://cloud.r-project.org/"))
```



```{r echo=TRUE, message=FALSE, warning=FALSE, results='hide'}

install.packages("readxl")
install.packages("dplyr")
install.packages("lubridate")
install.packages("ggplot2")
install.packages("tidyr")
install.packages("knitr")
install.packages("broom")
install.packages("rmarkdown")

```

```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
library(readxl)
library(dplyr)
library(lubridate)
library(tidyr)
library(broom)
library(ggplot2)
```


```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}

file.choose()
Secretarios_de_saude_CO <- read_excel("C:/Users/Aleno/OneDrive/Área de Trabalho/Lista 3/_Secretarios de saúde 2.xlsx")
Secretarios_de_saude_Norte <- read_excel("C:/Users/Aleno/OneDrive/Área de Trabalho/Lista 3/_Secretarios de saúde 2.xlsx", sheet = "Norte")
Secretarios_de_saude_Nordeste <- read_excel("C:/Users/Aleno/OneDrive/Área de Trabalho/Lista 3/_Secretarios de saúde 2.xlsx", sheet = "Nordeste")
Secretarios_de_saude_Sudeste <- read_excel("C:/Users/Aleno/OneDrive/Área de Trabalho/Lista 3/_Secretarios de saúde 2.xlsx", sheet = "Sudeste")
Secretarios_de_saude_Sul <- read_excel("C:/Users/Aleno/OneDrive/Área de Trabalho/Lista 3/_Secretarios de saúde 2.xlsx", sheet = "Sul")

```



```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
prepare_data <- function(df, nome_regiao) {df %>% 
mutate( Mandato_Inicio = 
as.numeric(Mandato_Inicio), Mandato_Final = as.numeric(Mandato_Final), 
duracao_mandato = (Mandato_Final - Mandato_Inicio) + 1 ) %>% 
select(Gênero, duracao_mandato) %>% mutate(nome_regiao)}

```


```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}
secretarios_combinados <- bind_rows(
  prepare_data(Secretarios_de_saude_CO, "Centro-Oeste"),
  prepare_data(Secretarios_de_saude_Norte, "Norte"),
  prepare_data(Secretarios_de_saude_Nordeste, "Nordeste"),
  prepare_data(Secretarios_de_saude_Sudeste, "Sudeste"),
  prepare_data(Secretarios_de_saude_Sul,"Sul"))
```

```{r message=FALSE, warning=FALSE, include=FALSE, results='hide'}

secretarios_combinados <- na.omit(secretarios_combinados)
```

# Hipótese 


---

Com base nos dados anteriormente apresentados, testaremos aqui se existe relação entre a duração dos mandatos dos secretarios da saúde no Brasil com o gênero.


# Modelo estatístico 

---
 
O modelo que usamos aqui foi a regressão linear, pois esta é utilizada para verificar se existe significancia estatística entreduas variáveis. 


---


```{r echo=TRUE}
modelo_lm <- lm(duracao_mandato ~ Gênero, data = secretarios_combinados)

# Resumo do modelo
tidy (modelo_lm)
glance (modelo_lm)
```


---

```{r echo=FALSE}
modelo_lm %>%
  augment(secretarios_combinados) %>%
ggplot (aes(x = Gênero, y = duracao_mandato)) +
  geom_point() + 
  geom_smooth(method = "lm", color = "blue", se = TRUE) +  
  labs(title = "Regressão de Duração de Mandato por Gênero", x = "Gênero", y = "Duração de Mandato") +
  theme_minimal()
```


---


```{r echo=FALSE}
modelo_lm %>%
  augment(secretarios_combinados) %>%
ggplot(aes(x = Gênero, y = duracao_mandato)) +
  geom_jitter(width = 0.2, height = 0) + 
  stat_summary(fun = mean, geom = "point", color = "blue", size = 3) +
  stat_summary(fun = mean, geom = "line", color = "blue", size = 1, aes(group = 1)) +  
  labs(title = "Média de Duração de Mandato por Gênero", x = "Gênero", y = "Duração de Mandato") +
  theme_minimal()

```

